### ISSUE TITLE
Total Duration of the dataset?

### ISSUE THREAD

**Issue by ethman** [qjyxdzqqyq/MetaMIDIDataset#1]
Hi MetaMIDI people!

Thanks for sharing such a cool project! Are there any statistics about the duration (in seconds) of the MIDI files in the dataset (i.e., if it were synthesized into audio)? Specifically, mean, median, std. dev. duration per song? As well as total duration of the whole dataset?

Thanks!

-Ethan

**Comment by lukewys** [comment]
I have checked with my own copy of dataset: 433527 files (can be read by pretty_midi), total duration of 19224.36 hours, mean: 161.82 seconds, std: 179.49 seconds.

**Comment by ethman** [comment]
Thanks Yusong!
